name: CI

on: push

permissions:
  contents: write

jobs:
  ci-back-end:
    name: Build and test back-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Check PHP syntax
        run: find . -type f -name '*.php' -exec php -l {} \;

  format-fix:
    name: Fix source code format with Prettier
    needs: ci-back-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm install prettier @prettier/plugin-php prettier-plugin-blade
      - run: npm run format:fix
      - run: git add .
      - run: git config --global user.email <>
      - run: git config --global user.name "GitHub Actions (format-fix)"
      - run: git commit -m "[AUTO] Fix source code format with Prettier" || echo "Files already correctly formatted."
      - run: git push
